# Generated by Django 3.0.6 on 2020-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='point',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
