# Generated by Django 3.0.6 on 2020-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='professor_name',
            field=models.TextField(null=True),
        ),
    ]
