# Generated by Django 3.0.6 on 2020-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_professor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='professor_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
